[build]
  command = "npm run build"
  publish = "public"
  functions = "workers-site"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200